name: "Setup R environment"
runs:
  using: 'composite'
  steps:
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        key: ${{ matrix.config.os }}-r-${{ matrix.config.r }}-${{ hashFiles('**/README.md') }}
        path: |
          ~/
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.config.r }}
        use-public-rspm: true
    - name: Install system dependencies for curl
      shell: bash
      run: sudo apt-get install -y libcurl4-openssl-dev
    - name: Install dependencies
      shell: bash
      run: |
        Rscript -e "install.packages('nflreadr')"
        Rscript -e "install.packages('piggyback')"
        Rscript -e "install.packages('tidyverse')"
        Rscript -e "install.packages('ffscrapr')"
        Rscript -e "install.packages('nflfastR')"