name: "Create and Upload Draft Data"

on:
  schedule:
    # At 00:00 every day in May
    - cron: "0 0 * 5 *"
  workflow_dispatch:

jobs:
  create_environment:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-22.04, r: "4.4" }
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          key: ${{ matrix.config.os }}-r-${{ matrix.config.r }}-${{ hashFiles('**/README.md') }}
          path: |
            ~/
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true
      - name: Install dependencies
        run: Rscript -e "install.packages(c('nflreadr', 'piggyback', 'tidyverse'))"

  handle_draft_data:
    runs-on: ubuntu-latest
    needs: create_environment
    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Data handling
        run: Rscript -e "source('R/draft/rfl-scrape-draft.R', echo = TRUE)"
