name: "Create and Upload Draft Data"

on:
  schedule:
    # At 00:00 every day in May
    - cron: '0 0 * 5 *'
  workflow_dispatch:

jobs:
  handle_draft_data:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: Rscript -e "install.packages(c('nflreadr', 'piggyback', 'dplyr', 'tidyr', 'jsonlite', 'readr'))"
      - name: Data handling
        run: Rscript -e "source('R/draft/rfl-scrape-draft.R', echo = TRUE)"