name: "Setup R environment"

on:
  workflow_dispatch:
    
jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build production image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/rfl-data:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - run: ls -l

