name: "Setup R environment"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: Rscript -e "install.packages(c('nflreadr', 'piggyback', 'dplyr', 'tidyr', 'jsonlite', 'readr'))"
