name: "Setup R environment"

on:
  workflow_dispatch:
    
jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - run: ls -l

