on:
  workflow_call:
  workflow_dispatch:

name: setup_r

jobs:
  create_data:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages: |
            ropensci/piggyback
            tidyverse/tidyverse
            nflverse/nflreadr
