name: "Create and Upload Starter Data"

on:
  schedule:
    # every tuesday at 8 am from september to december
    - cron: '0 6 * 9-12 2'
    # every thursday ar 16 pm from september to december
    - cron: '0 14 * 9-12 4'
  workflow_dispatch:

jobs:
  handle_data:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-22.04, r: "4.4" }
    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup-r
      - name: Data handling
        run: Rscript -e "source('R/starter/rfl-weekly-starter-since-2020.R', echo = TRUE)"
