name: "Create and Upload Starter Data"

on:
  schedule:
    # every tuesday at 8 am from september to december
    - cron: '0 6 * 9-12 2'
    # every thursday ar 16 pm from september to december
    - cron: '0 14 * 9-12 4'
  workflow_dispatch:

jobs:
  setup_environment:
    uses: ./.github/workflows/setup-r.yml
  handle_starter_data:
    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Data handling
        run: Rscript -e "source('R/starter/rfl-weekly-starter-since-2020.R', echo = TRUE)"
