name: "Test"

on:
  workflow_dispatch:

jobs:
  handle_trade_data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-r-environment-${{ hashFiles('**/package-lock.json') }}
          path: |
            ~/
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
