on:
  # schedule:
    # At 15:15 on Thursdays every week in Sep - Jan
    # - cron: '15 15 * 9-12,1 4'
    # At 15:15 on the 15th day of each month from Feb -> Aug
    # - cron: '15 15 15 2-8 *'
  workflow_dispatch:

name: upload_rfl_data

jobs:
  upload_rfl_data:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Cache Docker images
        id: cache
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('README.md') }}
      - name: Check Cache
        run: |
          echo "Cache hit: ${{ steps.cache.outputs.cache-hit }}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: Rscript -e "install.packages(c('nflreadr', 'piggyback', 'dplyr', 'tidyr', 'jsonlite', 'margrittr', 'readr'))"
      - name: Data handling
        run: Rscript -e "source('R/draft/rfl-scrape-draft.R')"
