name: "Test"

on:
  workflow_dispatch:

jobs:
  handle_trade_data:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-22.04, r: "4.4" }
    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          key: ${{ matrix.config.os }}-r-${{ matrix.config.r }}-${{ hashFiles('**/README.md') }}
          path: |
            ~/
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true
      - name: Install dependencies
        run: Rscript -e "install.packages(c('nflreadr', 'piggyback', 'tidyverse'))"
