on:
  # schedule:
    # At 15:15 on Thursdays every week in Sep - Jan
    # - cron: '15 15 * 9-12,1 4'
    # At 15:15 on the 15th day of each month from Feb -> Aug
    # - cron: '15 15 15 2-8 *'
  workflow_dispatch:

name: upload_rfl_data

jobs:
  create_data:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            ropensci/piggyback
            r-lib/pkgload
            tidyverse/tidyverse
            nflverse/nflreadr

      - name: Archive nflverse release
        run: Rscript -e "source('R/draft/rfl-scrape-draft.R')"
