on:
  # schedule:
    # At 15:15 on Thursdays every week in Sep - Jan
    # - cron: '15 15 * 9-12,1 4'
    # At 15:15 on the 15th day of each month from Feb -> Aug
    # - cron: '15 15 15 2-8 *'
  workflow_dispatch:

name: upload_rfl_data

jobs:
  upload_rfl_data:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-cache-v1
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: Rscript -e "install.packages(c('nflreadr', 'piggyback', 'tidyverse'))"
      - name: Data handling
        run: Rscript -e "source('R/draft/rfl-scrape-draft.R')"
