name: "Create and Upload Trade Data"

on:
  schedule:
    # At 00:00 every day in may
    - cron: "0 22 * 5 *"
    # every tuesday at 9 mez
    - cron: "0 7 * * 2"
    # every thursday at 17 mez
    - cron: "0 16 * * 4"
  workflow_dispatch:

jobs:
  handle_data:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-22.04, r: "4.4" }
    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup-r
      - name: Data handling
        run: Rscript -e "source('R/trades/rfl-scrape-trades.R', echo = TRUE)"
