name: "Create and Upload Trade Data"

on:
  schedule:
    # At 00:00 every day in May
    - cron: '0 0 * 5 *'
    # Once every week on thursday 18 MEZ
    - cron: '0 16 * * 4'
  workflow_dispatch:

jobs:
  handle_draft_data:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            tidyverse/dplyr
            tidyverse/tidyr
            jeroen/jsonlite
            tidyverse/readr
            tidyverse/lubridate
            ropensci/piggyback
      - name: Data handling
        run: Rscript -e "source('R/trades/rfl-scrape-trades.R', echo = TRUE)"
