stages:
  - create-csv
  - artifact-to-git

create-elo-data:
  stage: create-csv
  image: rocker/tidyverse:latest
  before_script:
    - Rscript -e "install.packages('nflreadr')"
  script:
    - Rscript rfl-elo.R
    - Rscript rfl-player-elo.R
  artifacts:
    paths:
      - output.csv
      - player-elo.csv
  only:
    - schedules

artifact-to-git:
  stage: artifact-to-git
  image: ubuntu:latest
  needs:
    - job: create-elo-data
      artifacts: true
  before_script:
    - apt-get update
    - apt-get install -y git
    - git config --global user.email "mail@jakob-eschler.de"
    - git config --global user.name "Jakob Eschler"
  script:
    - git clone $GITLAB_URL
    - cd rfl
    - cp $CI_PROJECT_DIR/output.csv data/elo/rfl-elo-$CURRENT_YEAR.csv
    - git add data/elo/rfl-elo-$CURRENT_YEAR.csv
    - cp $CI_PROJECT_DIR/player-elo.csv data/elo/rfl-player-elo-$CURRENT_YEAR.csv
    - git add data/elo/rfl-player-elo-$CURRENT_YEAR.csv
    - git commit -m "rfl elo data via pipepline hinzugefügt"
    - git push origin main
  only:
    - schedules
